# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DelayApi < Formula
  desc "simple wait& response api for timeout test"
  homepage "https://github.com/applegreengrape/delay-api"
  version "0.0.3"
  depends_on :macos

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/applegreengrape/delay-api/releases/download/v0.0.3/delay-api_0.0.3_darwin_amd64.zip"
      sha256 "6509133acbc16535c6d64fb9a249bf3f96939c8b63d64bf553fd9814880a1274"

      def install
        bin.install "wait"
      end
    end
  end
end
