# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TimeoutChecker < Formula
  desc "simple wait& response api for timeout test"
  homepage "https://github.com/applegreengrape/timeout-checker"
  version "0.0.4"
  depends_on :macos

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/applegreengrape/timeout-checker/releases/download/v0.0.4/timeout-checker_0.0.4_darwin_amd64.zip"
      sha256 "c2535aa791d50aa919dd210b70068065d9db94f4ab221176a61510be44688aeb"

      def install
        bin.install "checker-api"
      end
    end
  end
end
