# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TimeoutChecker < Formula
  desc "simple wait& response api for timeout test"
  homepage "https://github.com/applegreengrape/timeout-checker"
  version "0.1.0"
  depends_on :macos

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/applegreengrape/timeout-checker/releases/download/v0.1.0/timeout-checker_0.1.0_darwin_amd64.zip"
      sha256 "8dc0c47e924b03598ddd397eba41dcdb87e11c557d7bbebcd65fc9208a2bb6c4"

      def install
        bin.install "checker-api"
      end
    end
  end
end
