# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TimeoutChecker < Formula
  desc "simple wait& response api for timeout test"
  homepage "https://github.com/applegreengrape/timeout-checker"
  version "0.0.5"
  depends_on :macos

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/applegreengrape/timeout-checker/releases/download/v0.0.5/timeout-checker_0.0.5_darwin_amd64.zip"
      sha256 "ea28a7946b57860ea2958980bae724bb42e2d0145528b14b9994da7d79525292"

      def install
        bin.install "checker-api"
      end
    end
  end
end
